2024-12-21 15:23:15,380 - src.main - INFO - Periodic sync completed: {'status': 'success', 'records_synced': 0, 'message': 'Successfully synced 0 records'}
2024-12-21 15:23:19,789 - src.db.init_db - INFO - Database initialized successfully
2024-12-21 15:23:19,801 - src.main - INFO - Application startup completed
2024-12-21 15:23:19,801 - src.main - INFO - Periodic sync completed: {'status': 'success', 'records_synced': 0, 'message': 'Successfully synced 0 records'}
2024-12-21 15:23:41,480 - src.db.init_db - INFO - Database initialized successfully
2024-12-21 15:23:41,490 - src.main - INFO - Application startup completed
2024-12-21 15:23:41,491 - src.main - INFO - Periodic sync completed: {'status': 'success', 'records_synced': 0, 'message': 'Successfully synced 0 records'}
2024-12-21 15:28:41,478 - src.main - INFO - Periodic sync completed: {'status': 'success', 'records_synced': 0, 'message': 'Successfully synced 0 records'}
2024-12-21 15:33:27,685 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\kes\anaconda3\lib\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-12-21 15:33:41,490 - src.main - INFO - Periodic sync completed: {'status': 'success', 'records_synced': 0, 'message': 'Successfully synced 0 records'}
